POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "username": "moses", 
    "email": "moses2@gmail.com", 
    "password": "moses"
}
###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "moses@gmail.com",
    "password": "moses"
}
### below uses token for moses2@gmail.com
DELETE http://localhost:3000/event/delete/6238c235c3a5af530fa1feff
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibW9zZXMiLCJlbWFpbCI6Im1vc2VzQGdtYWlsLmNvbSIsImlhdCI6MTY0Nzc5MDA4M30.vX6yi6xnjf7yeisKbuYURgbq61XJWKMaxQxZPbMIfao
### 
POST http://localhost:3000/event/create
Authorization:  Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoibW9zZXMiLCJlbWFpbCI6Im1vc2VzQGdtYWlsLmNvbSIsImlhdCI6MTY0Nzc5MDA4M30.vX6yi6xnjf7yeisKbuYURgbq61XJWKMaxQxZPbMIfao
Content-Type: application/json